Basic login
andreasalstrup/CoShare pull request #51
Opened 2023-11-24 14:22 UTC by emilnormann

Fixed comments.
Helpers not in separate file because of dependencies.
EAS builds locally so should work.

2023-11-26 18:32 UTC, UnluckyBird commented on app/(login)/CreateAccountScreen.tsx
> +export default class CreateAccountScreen extends Component<Props, State> {
React does not recommend defining components as classes, but instead as functions per: https://react.dev/reference/react/Component
They have a guide for migration here: https://react.dev/reference/react/Component#alternatives

2023-11-26 18:33 UTC, UnluckyBird commented on app/(login)/LoginScreen.tsx
> +export default class loginScreen extends Component<Props, State> {
React does not recommend defining components as classes, but instead as functions per: https://react.dev/reference/react/Component
They have a guide for migration here: https://react.dev/reference/react/Component#alternatives

2023-11-28 07:49 UTC, andreasalstrup commented on .github/workflows/build.yml
Do not change

2023-11-28 07:49 UTC, andreasalstrup commented on .github/workflows/update.yml
Do not change

2023-11-28 07:52 UTC, UnluckyBird commented on .github/workflows/update.yml
Don't change

2023-11-28 07:53 UTC, UnluckyBird commented on app/(login)/LoginScreen.tsx
> +  text: any
string

2023-11-28 08:27 UTC, andreasalstrup requested changes
LGTM just fix comments

2023-11-28 09:20 UTC, andreasalstrup commented on constants/Database.ts
> +peers: ['https://130.225.39.205:8080/gun'],
```suggestion
peers: ['http://130.225.39.205:8080/gun'],
```

2023-11-28 09:25 UTC, UnluckyBird commented on app/(login)/CreateAccountScreen.tsx
> +  function validatePhone (phone : string) {
can be made shorter with `const validatePhone : boolean (phone : string) => phone.length == 8`

2023-11-28 09:26 UTC, UnluckyBird commented on app/(login)/CreateAccountScreen.tsx
> +  function validatePass (pass : string) {
`const validatePass : boolean (pass: string) => pass.length > 7`

2023-11-28 09:29 UTC, UnluckyBird commented on app/(login)/CreateAccountScreen.tsx
> +  function toggleHidePassword () {
`const toggleHidePassword = () => setHidePassword(!hidePassword)`

2023-11-29 08:53 UTC, UnluckyBird approved these changes

2023-11-29 09:40 UTC, merged